max_email_length: 255
max_first_name_length: 50
max_last_name_length: 50
max_username_length: 50
min_username_length: 6
min_password_length: 6
remember_me: "remember"
forget_me: "forget"
reset_expired: 2
default_gravatar_size: 80
medium_image_size: "300x300>"
thumb_image_size: "270x152>"
placeholder_path: "/images/:style/missing.png"
per_page:
  user: 10
  tour: 10
  trip: 10
  booking_requests: 10
editor_height: 400
lowest_star: 0
highest_star: 5
lowest_max_people: 0
highest_max_people: 100
trips_tab: "trips"
contact_number: "0165-888-8888"
