max_first_name_length: 50
max_last_name_length: 50
max_username_length: 50
min_username_length: 6
remember_me: "remember"
forget_me: "forget"
reset_expired: 2
default_gravatar_size: 80
medium_image_size: "300x300>"
avatar_thumb_image_size: "150x150>"
thumb_image_size: "270x152>"
placeholder_path: "/images/:style/missing.png"
per_page:
  user: 10
  tour: 10
  trip: 10
  booking_request: 10
  review: 10
themes:
  user: 'user'
editor_height: 400
small_editor_height: 200
lowest_star: 0
highest_star: 10
lowest_max_people: 0
highest_max_people: 100
trips_tab: "trips"
contact_number: "0165-888-8888"
like: "like"
unlike: "unlike"
omniauth:
  facebook: "Facebook"
  google: "Google"
